apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: mern-client
  ports:
  - protocol: TCP
    port: 3000        # Port interne du service
    targetPort: 3000   # Port du conteneur
  type: LoadBalancer
