apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: mern-server
  ports:
  - protocol: TCP
    port: 5000        # Port interne du service
    targetPort: 5000   # Port du conteneur
  type: LoadBalancer   # Type LoadBalancer
